[package]
name = "tracexec"
version = "0.0.5"
edition = "2021"
authors = ["Levi Zim <rsworktech@outlook.com>"]
description = "A small utility for tracing execve{,at}"
license = "GPL-2.0"
readme = "README.md"
repository = "https://github.com/kxxt/tracexec"
homepage = "https://github.com/kxxt/tracexec"
keywords = ["trace", "ptrace", "strace", "utility"]
categories = ["command-line-utilities", "development-tools::debugging"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
color-eyre = "0.6.2"
nix = { version = "0.27.1", features = ["ptrace", "process", "feature"] }
strum = { version = "0.26.1", features = ["derive"] }
log = "0.4"
cfg-if = "1.0.0"
owo-colors = { version = "4.0.0", package = "kxxt-owo-colors", features = [
    "global-colorized-control",
] }
shell-quote = { version = "0.5.0" }
seccompiler = { version = "0.4.0", optional = true }
atoi = "2.0.0"
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
directories = "5.0.1"
lazy_static = "1.4.0"
ratatui = "0.26.2"
crossterm = { version = "0.27.0", features = ["event-stream"] }
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = "0.7.10"
futures = "0.3.30"
signal-hook = "0.3.17"
better-panic = "0.3.0"

[features]
default = ["seccomp-bpf"]
seccomp-bpf = ["dep:seccompiler"]
