[package]
name = "tracexec"
version = "0.0.0-experimental.1"
edition = "2021"
author = "Levi Zim <rsworktech@outlook.com>"
description = "A small utility to trace command execution."
license = "GPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
color-eyre = "0.6.2"
nix = { version = "0.27.1", features = ["ptrace", "process"] }
strum = { version = "0.25.0", features = ["derive"] }
log = "0.4"
pretty_env_logger = "0.5"